### ISSUE TITLE
bpfilter error log

### ISSUE THREAD

**Issue by barzag** [AdityaGarg8/pve-edge-kernel-t2#2]
Hello, How do I delete the bpfilter error message that floods my Proxmox console? Do you have any ideas?

**Comment by AdityaGarg8** [comment]
Are you using proxmox official kernel or kernel from this repo?

**Comment by barzag** [comment]
No this repo 6.1-1

**Comment by AdityaGarg8** [comment]
Did you try 6.5 official kernel with the commands I sent in the other issue?

**Comment by AdityaGarg8** [comment]
Is it resolved in the new kernel?

**Comment by barzag** [comment]
Yes 👍🏻
